
name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure and solver
        run: |
          cmake -B build
          cmake --build build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: build
