name: CPack_solver_app

on:
   push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        
        touch amount.txt
        
        mkdir _build && cd _build
        
        cmake .. -DCPACK_GENERATOR="TGZ"
        cmake --build . --target package
        
        find . -executable | wc -l >> amount.txt
        
        cpack -G "DEB"
        cpack -G "RPM"
        
        mkdir artifacts
        mv *.tar.gz artifacts
        mv *.deb .artifacts
        mv *.rpm artifacts
           
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts
